simpleArgs: &simple-args
  document:
    [
      [],
      "did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN",
      [],
      [
        [
          "did:indy2:indy_besu:RQDxoJ2Mz3WuyqaqsjVTdN#KEY-1",
          "Ed25519VerificationKey2018",
          "did:indy2:testnet:N22WedHLJdFf4yMaDXdhJcL97",
          "HAFkhqbPbor781QCMfNvr6oQTTixK9U7gZmDV7pszTHp",
          "",
        ],
      ],
      [
        [
          "did:indy2:indy_besu:RQDxoJ2Mz3WuyqaqsjVTdN#KEY-1",
          ["1", "1", "1", "1", "1"],
        ],
      ],
      [],
      [],
      [],
      [],
      [],
      [],
    ]
  numberOfAccounts: &number-of-accounts 1
  timeOfTest: &time-of-test 10

test:
  name: createDid Test
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: createDid
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txDuration: *time-of-test
      rateControl:
        type: fixed-rate
        opts:
          tps: 40
      workload:
        module: benchmarks/scenario/IndyDidRegistry/createDid.js
        arguments: *simple-args

monitors:
  resource:
    - module: docker
      options:
        interval: 5
        cpuUsageNormalization: true # Normalizes CPU usage values to a 0-100% range
        containers:
          - /node1
          - /node2
          - /node3
          - /node4
          - /node5
          - /node6
        stats:
          memory:
            max: true
            avg: true
          cpu:
            max: true # Enable monitoring of max CPU usage
            avg: true # Enable monitoring of average CPU usage
          networkIO:
            enabled: true # Enable monitoring of network I/O
          diskIO:
            enabled: true # Enable monitoring of disk I/O

        charting:
          bar:
            metrics: [Memory(avg), CPU%(avg)]
          polar:
            metrics: [all]

observer:
  type: local
  interval: 5
