simpleArgs: &simple-args
  _revocation:
    [
      "1.0.0",
      "revReg123",
      "CL_ACCUM",
      "did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN/anoncreds/v0/CLAIM_DEF/did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN/anoncreds/v0/SCHEMA/ScoreSch1/1.0",
      "test-tag",
      "value123",
      "did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN",
    ]

  numberOfAccounts: &number-of-accounts 1
  timeOfTest: &time-of-test 10

test:
  name: createRevocationRegistry Test
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: createRevocationRegistry
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txDuration: *time-of-test
      rateControl:
        type: fixed-rate
        opts:
          tps: 120
      workload:
        module: benchmarks/scenario/RevocationRegistry/createRevocationRegistry.js
        arguments: *simple-args

monitors:
  resource:
    - module: docker
      options:
        interval: 5
        cpuUsageNormalization: true # Normalizes CPU usage values to a 0-100% range
        containers:
          - /node1
          - /node2
          - /node3
          - /node4
          - /node5
          - /node6
        stats:
          memory:
            max: true
            avg: true
          cpu:
            max: true # Enable monitoring of max CPU usage
            avg: true # Enable monitoring of average CPU usage
          networkIO:
            enabled: true # Enable monitoring of network I/O
          diskIO:
            enabled: true # Enable monitoring of disk I/O

        charting:
          bar:
            metrics: [Memory(avg), CPU%(avg)]
          polar:
            metrics: [all]

observer:
  type: local
  interval: 5
